version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
          # You can add additional steps or commands if needed
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             # Add code to build/compile the back-end
          # You can add additional steps or commands if needed
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflows:
  version: 2
  default:
    jobs:
      - build-frontend
      - build-backend
      # Add other jobs to the workflow as needed
